<?php
/**
 * @file
 * Custom functionality for a wind farm database.
 */
 
 /**
 * Implements hook_help().
 */
 
 function windfarms_help($path, $arg) {
	 switch($path) {
		 case 'admin/help#windfarms':{
		     $ret_val = '<h3>' .t('About') . '</h3>';
		     $ret_val .= '<p>' .t('The Wind Farms module makes it easy to manage a database of wind farms.'). '</p>';
		     return $ret_val;
			 break;
		 }
	 }
 }
 
 /**
 * Implements hook_permission().
 */
 
 function windfarms_permission() {
	 return array(
	 	'administer wind farms' => array(
	 		'title' => t('Administer Wind Farms'),
	 		'description' => t('Perform administrative tasks on Wind Farms functionality'),
     ),
   );
 }
 
  /**
 * Implements hook_menu().
 */
 
 function windfarms_menu() {
	 $items = array();
	 
	 //Admin configuration group.
	 $items['admin/config/windfarms'] = array(
	   'title' => 'Wind Farms',
	   'description' => 'Administer Wind Farms',
	   'access arguments' => array('administer wind farms'),
	 );
	 
	 //Admin configuration - Settings.
	 $items['admin/config/windfarms/manage'] = array(
	   'title' => 'Wind farm settings',
	   'description' => 'Manage Wind Farm settings and configurations.',
	   'access arguments' => array('administer wind farms'),
	   'page callback' => 'drupal_get_form', 
	   'page arguments' => array('windfarms_admin_settings_form'),
	 );
	 
	 return $items;
 }
 
  /**
 * Implements hook_form().
 */
 
 function windfarms_admin_settings_form($node, &$form_state) {
	 $form = array();
	 
	 $form['overview'] = array(
	 	'#markup' => t('This interface allows administrators to manage general Wind Farm Settings'),
	 	'#prefix' => '<p>',
	 	'#suffix' => '</p>',
	 );
	 
	 $form['windfarms_gmap'] = array(
	 	'#title' => t('Enable Google Maps'),
	 	'#description' => t('When enabled, Google Maps will be rendered if latitude and longitude are known.'),
	 	'#type' => 'checkbox',
	 	'#default_value' => 1,
	 );
	 
	 $form['default_center'] = array(
	 	'#title' => t('Map Center'),
	 	'#description' => t('Location of the center of the map of wind farms.'),
	 	'#type' => 'fieldset',
	 	'#collapsible' => TRUE,
	 	'#collapsed' => FALSE,
	 );
	 
	 
	 $form['default_center']['windfarms_default_center_lat'] = array(
	 	'#title' => t('Latitude'),
	 	'#description' => t('Signed degrees format (DDD.dddd)'),
	 	'#type' => 'textfield',
	 	'#default_value' => 42.91455,
	 	'#required' => TRUE,
	 );
	 
	 $form['default_center']['windfarms_default_center_long'] = array(
	 	'#title' => t('Longitude'),
	 	'#description' => t('Signed degrees format (DDD.ddd)'),
	 	'#type' => 'textfield',
	 	'#default_value' => -75.569851 ,
	 	'#required' => TRUE,
	 );
	 
	 $options = range(0, 20, 1);
	 $options[0] = t('0 - Furthest');
	 $options[20] = t('20 - Closest');
	 
	 $form['windfarms_default_gmap_zoom'] = array(
	 	'#title' => t('Google Map zoom'),
	 	'#description' => t('Default level of zoom, between 0 and 20'),
	 	'#type' => 'select',
	 	'#options' => $options,
	 	'#default_value' => 8,
	 	'#required' => TRUE,
	 );
	 
	 $form['submit'] = array(
	 	'#type' => 'submit',
	 	'#value' => t('Save'),
	 );
	 
	 return $form;
 }
